#!/usr/bin/env python

# Copyright 2019, MontaVista Software, LLC
# SPDX-License-Identifier: MIT

import sys
import tuf
from tuf_manifest.tuf_manifest_repo import *

if __name__ == '__main__':
    arguments = parse_arguments()

    try:
        process_arguments(arguments)
    except (tuf.exceptions.Error) as e:
        sys.stderr.write('Error: ' + str(e) + '\n')
        sys.exit(1)

    # Successfully created or updated the TUF repository.
    sys.exit(0)
